services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: laravel
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build: .
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - postgres

volumes:
  data: