---
- name: Actualizar el sistema
  apt:
    upgrade: yes
    update_cache: yes

- name: Instalar software-properties-common
  apt:
    name: 
      - software-properties-common
      - curl
      - nmap
      - htop
      - dnsutils
      - net-tools
      - mysql-client
      - postgresql-client
    state: present
